# Generated by Django 3.2.13 on 2022-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_auto_20220430_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='api_app.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='utensils',
            field=models.ManyToManyField(related_name='utensils', to='api_app.Utensil'),
        ),
    ]
